### ISSUE TITLE
SVG file

### ISSUE THREAD

**Issue by TheKitty** [tannewt/basicpython#1]
Looking to convert the SVG file to animated GIF for the newsletter, trying with https://loading.io/animation/icon/

Can your capture tool output to GIF directly?

**Comment by tannewt** [comment]
No, unfortunately. I used `termtosvg`.

**Comment by TheKitty** [comment]
Darn, the online converters aren't picking up the animation

**Comment by TheKitty** [comment]
Can you scale to 550 px?

**Comment by tannewt** [comment]
I don't know how to do that either.

**Comment by TheKitty** [comment]
Ok, thanks
